/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ForClinicsRouteImport } from './routes/for-clinics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedToxcheckRouteImport } from './routes/_authenticated/toxcheck'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedSectionSectionIdRouteImport } from './routes/_authenticated/section.$sectionId'
import { Route as AuthenticatedFormsFormIdRouteImport } from './routes/_authenticated/forms.$formId'
import { Route as AuthenticatedDiagnosticMetricIdRouteImport } from './routes/_authenticated/diagnostic.$metricId'
import { Route as AuthenticatedBoxBoxIdRouteImport } from './routes/_authenticated/box.$boxId'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClinicsRoute = ForClinicsRouteImport.update({
  id: '/for-clinics',
  path: '/for-clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToxcheckRoute = AuthenticatedToxcheckRouteImport.update({
  id: '/toxcheck',
  path: '/toxcheck',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectionSectionIdRoute =
  AuthenticatedSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsFormIdRoute =
  AuthenticatedFormsFormIdRouteImport.update({
    id: '/$formId',
    path: '/$formId',
    getParentRoute: () => AuthenticatedFormsRoute,
  } as any)
const AuthenticatedDiagnosticMetricIdRoute =
  AuthenticatedDiagnosticMetricIdRouteImport.update({
    id: '/diagnostic/$metricId',
    path: '/diagnostic/$metricId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoxBoxIdRoute = AuthenticatedBoxBoxIdRouteImport.update({
  id: '/box/$boxId',
  path: '/box/$boxId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/for-clinics': typeof ForClinicsRoute
  '/waitlist': typeof WaitlistRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/intake': typeof AuthenticatedIntakeRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/toxcheck': typeof AuthenticatedToxcheckRoute
  '/box/$boxId': typeof AuthenticatedBoxBoxIdRoute
  '/diagnostic/$metricId': typeof AuthenticatedDiagnosticMetricIdRoute
  '/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/section/$sectionId': typeof AuthenticatedSectionSectionIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/for-clinics': typeof ForClinicsRoute
  '/waitlist': typeof WaitlistRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/intake': typeof AuthenticatedIntakeRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/toxcheck': typeof AuthenticatedToxcheckRoute
  '/': typeof AuthenticatedIndexRoute
  '/box/$boxId': typeof AuthenticatedBoxBoxIdRoute
  '/diagnostic/$metricId': typeof AuthenticatedDiagnosticMetricIdRoute
  '/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/section/$sectionId': typeof AuthenticatedSectionSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-clinics': typeof ForClinicsRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRouteWithChildren
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/toxcheck': typeof AuthenticatedToxcheckRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/box/$boxId': typeof AuthenticatedBoxBoxIdRoute
  '/_authenticated/diagnostic/$metricId': typeof AuthenticatedDiagnosticMetricIdRoute
  '/_authenticated/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/_authenticated/section/$sectionId': typeof AuthenticatedSectionSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/for-clinics'
    | '/waitlist'
    | '/assessments'
    | '/calendar'
    | '/connections'
    | '/forms'
    | '/intake'
    | '/records'
    | '/timeline'
    | '/toxcheck'
    | '/box/$boxId'
    | '/diagnostic/$metricId'
    | '/forms/$formId'
    | '/section/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/for-clinics'
    | '/waitlist'
    | '/assessments'
    | '/calendar'
    | '/connections'
    | '/forms'
    | '/intake'
    | '/records'
    | '/timeline'
    | '/toxcheck'
    | '/'
    | '/box/$boxId'
    | '/diagnostic/$metricId'
    | '/forms/$formId'
    | '/section/$sectionId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/for-clinics'
    | '/waitlist'
    | '/_authenticated/assessments'
    | '/_authenticated/calendar'
    | '/_authenticated/connections'
    | '/_authenticated/forms'
    | '/_authenticated/intake'
    | '/_authenticated/records'
    | '/_authenticated/timeline'
    | '/_authenticated/toxcheck'
    | '/_authenticated/'
    | '/_authenticated/box/$boxId'
    | '/_authenticated/diagnostic/$metricId'
    | '/_authenticated/forms/$formId'
    | '/_authenticated/section/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForClinicsRoute: typeof ForClinicsRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clinics': {
      id: '/for-clinics'
      path: '/for-clinics'
      fullPath: '/for-clinics'
      preLoaderRoute: typeof ForClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toxcheck': {
      id: '/_authenticated/toxcheck'
      path: '/toxcheck'
      fullPath: '/toxcheck'
      preLoaderRoute: typeof AuthenticatedToxcheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/section/$sectionId': {
      id: '/_authenticated/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/section/$sectionId'
      preLoaderRoute: typeof AuthenticatedSectionSectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$formId': {
      id: '/_authenticated/forms/$formId'
      path: '/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof AuthenticatedFormsFormIdRouteImport
      parentRoute: typeof AuthenticatedFormsRoute
    }
    '/_authenticated/diagnostic/$metricId': {
      id: '/_authenticated/diagnostic/$metricId'
      path: '/diagnostic/$metricId'
      fullPath: '/diagnostic/$metricId'
      preLoaderRoute: typeof AuthenticatedDiagnosticMetricIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/box/$boxId': {
      id: '/_authenticated/box/$boxId'
      path: '/box/$boxId'
      fullPath: '/box/$boxId'
      preLoaderRoute: typeof AuthenticatedBoxBoxIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFormsRouteChildren {
  AuthenticatedFormsFormIdRoute: typeof AuthenticatedFormsFormIdRoute
}

const AuthenticatedFormsRouteChildren: AuthenticatedFormsRouteChildren = {
  AuthenticatedFormsFormIdRoute: AuthenticatedFormsFormIdRoute,
}

const AuthenticatedFormsRouteWithChildren =
  AuthenticatedFormsRoute._addFileChildren(AuthenticatedFormsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRouteWithChildren
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedToxcheckRoute: typeof AuthenticatedToxcheckRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBoxBoxIdRoute: typeof AuthenticatedBoxBoxIdRoute
  AuthenticatedDiagnosticMetricIdRoute: typeof AuthenticatedDiagnosticMetricIdRoute
  AuthenticatedSectionSectionIdRoute: typeof AuthenticatedSectionSectionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRouteWithChildren,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedToxcheckRoute: AuthenticatedToxcheckRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBoxBoxIdRoute: AuthenticatedBoxBoxIdRoute,
  AuthenticatedDiagnosticMetricIdRoute: AuthenticatedDiagnosticMetricIdRoute,
  AuthenticatedSectionSectionIdRoute: AuthenticatedSectionSectionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForClinicsRoute: ForClinicsRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
